### ISSUE TITLE
Validation errors cannot be processed on latest version of fastapi

### ISSUE THREAD

**Issue by ave-satan** [smagafurov/fastapi-jsonrpc#55]
`fastapi==0.103.1` 
It's not giving `Validation error (code 6000)` for invalid parameters as it was before. Now they are `Internal error (code -32603)` instead because something breakes in library error processing.
Downgrading `fastapi` version to `0.98.0` helps to mitigate this error.

This code block no longer works https://github.com/smagafurov/fastapi-jsonrpc/blob/2049e1caed9ec1d50cdcb3066756cf983cb9eabe/fastapi_jsonrpc/__init__.py#L391-L397
It seems that `fastapi` introduced some kind of error wrapper and _some_ errors (not all of them) are not just plain dicts anymore.

Here is my traceback for the error
```
Traceback (most recent call last):
  File "/home/ave_satan/.pyenv/versions/3.11.1/envs/statements/lib/python3.11/site-packages/fastapi_jsonrpc/__init__.py", line 596, in _handle_exception
    yield
  File "/home/ave_satan/.pyenv/versions/3.11.1/envs/statements/lib/python3.11/site-packages/fastapi_jsonrpc/__init__.py", line 1147, in handle_req_to_resp
    resp = await self.handle_req(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ave_satan/.pyenv/versions/3.11.1/envs/statements/lib/python3.11/site-packages/fastapi_jsonrpc/__init__.py", line 1173, in handle_req
    return await route.handle_req(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ave_satan/.pyenv/versions/3.11.1/envs/statements/lib/python3.11/site-packages/fastapi_jsonrpc/__init__.py", line 865, in handle_req
    raise invalid_params_from_validation_error(RequestValidationError(errors))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ave_satan/.pyenv/versions/3.11.1/envs/statements/lib/python3.11/site-packages/fastapi_jsonrpc/__init__.py", line 393, in invalid_params_from_validation_error
    if err['loc'][:1] == ('body', ):
       ~~~^^^^^^^
TypeError: list indices must be integers or slices, not str
```

https://github.com/smagafurov/fastapi-jsonrpc/blob/2049e1caed9ec1d50cdcb3066756cf983cb9eabe/fastapi_jsonrpc/__init__.py#L391
`exc.errors()` on `0.98.0`:
```
[{'loc': ('body', 'accounts', 0, 'bank_code'), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}]
```

`exc.errors()` on `0.103.1`:
```python
[[ErrorWrapper(exc=ValidationError(model='Account', errors=[{'loc': ('bank_code',), 'msg': 'none is not an allowed value', 'type': 'type_error.none.not_allowed'}]), loc=('body', 'accounts', 0))]]
```

**Comment by smagafurov** [comment]
fixed

fastapi_jsonrpc==2.6.1
